### ISSUE TITLE
don't need deadsnakes repo

### ISSUE THREAD

**Issue by metachris** [erberg/neo-vagrant#1]
Since Ubuntu 16:10, Python 3.6 is available in the standard repositories. No need to import the deadsnakes repo.

https://github.com/erberg/neo-vagrant/blob/master/Vagrantfile#L68

**Comment by erberg** [comment]
The 'ubuntu/xenial64' box is 16.04. Maybe I'll switch to a 16.10 box. Simpler is better

**Comment by metachris** [comment]
Oh haha, mixed things up :-P

Why not use a 17.10 image?
